### ISSUE TITLE
there is a bug when filename contains a non-ascii character

### ISSUE THREAD

**Issue by mushanshitiancai** [kennethreitz/requests#2407] opened 2015-01-13 12:51 UTC
I ues python 2.7.9 and requests 2.5.1
when I do like this:

```
files = {'file1':('中文','hello')}
r = requests.post('http://test',files=files)
```

the request is like this(copy from fiddler):

```
Content-Disposition: form-data; name="file1"; filename*=utf-8''%E4%B8%AD%E6%96%87
```

I think the format of filename is wrong.

the right format should be:

```
Content-Disposition: form-data; name="file1"; filename="中文"
```

**Comment by mushanshitiancai** [comment] 2015-01-13 12:55
in requests\packages\urllib3\fields.py

```
def format_header_param(name, value):
    if not any(ch in value for ch in '"\\\r\n'):
        result = '%s="%s"' % (name, value)
        try:
            result.encode('ascii')
        except UnicodeEncodeError:
            pass
        else:
            return result
    if not six.PY3:  # Python 2:
        value = value.encode('utf-8')
    value = email.utils.encode_rfc2231(value, 'utf-8')
    value = '%s*=%s' % (name, value)
    return value
```

I think this is related code.

When the Content-Type is multipart/form-data,is it correct ues this function to format heaer?

**Comment by sigmavirus24** [comment] 2015-01-13 13:06
Duplicate of #2313. Please search for existing issues before opening new ones in the future.

**Closed by sigmavirus24** 2015-01-13 13:07 UTC
