### ISSUE TITLE
Environment http_proxy will cover the Session property s.proxies

### ISSUE THREAD

**Issue by syjiangrui** [kennethreitz/requests#2414] opened 2015-01-19 04:05 UTC
When I use a proxy in my code I find a problem. In the code below
```python
s = requests.Session()
s.proxies = {'http':'127.0.0.1:3128'}
r = s.get("http://www.apple.com")
```

If I set environmet var http_proxy='http://192.168.1.100:3128' then the request will use environment proxy rather than the proxy I have set in the code.
But if I use proxy like below the program will use the proxy which I set in the code.
```python
s = requests.Session()
r = s.get("http://www.apple.com", proxies={'http':'127.0.0.1:3128'})
```
Is there any issue?

**Comment by sigmavirus24** [comment] 2015-01-19 04:29
Possible duplicate of #2109

**Comment by Lukasa** [comment] 2015-01-19 08:58
Nope, it's a definite duplicate of #2018.

**Closed by Lukasa** 2015-01-19 08:58 UTC
