### ISSUE TITLE
No tests being run in CI against new pull requests

### ISSUE THREAD

**Issue by alexwlchan** [kennethreitz/requests#3746] opened 2016-12-02 19:39 UTC
It looks like there aren’t any tests being run in CI against pull requests, so there’s a bit of extra work for reviewers to get the patch locally and run the tests themselves. And running tests locally is more susceptible to environment-specific test quirks.

It looks like there used to be CI on older pull requests from <http://ci.kennethreitz.org>, but that seems to be unresponsive now. 😢 

Would you be interested in a patch that adds some config for Travis CI (and/or another CI service of your choice)?

**Comment by Lukasa** [comment] 2016-12-02 19:39
Sorry Alex, but this happens to all of us:

Closing as a dupe of #3739.

**Closed by Lukasa** 2016-12-02 19:39 UTC

**Comment by alexwlchan** [comment] 2016-12-02 19:41
And not even an old issue either! Wow, I’m really not with it today.

**Comment by Lukasa** [comment] 2016-12-02 19:42
:wink: We all have off days, nothing to be worried about there. Just thought it was funny.
