### ISSUE TITLE
No Content-Length header when POSTing or PUTing an empty Django InMemoryUploadedFile

### ISSUE THREAD

**Issue by CianciuStyles** [kennethreitz/requests#3977] opened 2017-04-20 09:57 UTC
I'm trying to send a PUT request passing as the data kwarg an instance of a InMemoryUploadedFile (which is the model Django uses for uploaded files, see for reference https://docs.djangoproject.com/en/1.10/ref/files/uploads/#django.core.files.uploadedfile.InMemoryUploadedFile), like this:

```
files = request.FILES.getlist('file')
for uploaded_file in files:
    [...]
    requests.put(upload_url, data=uploaded_file)
```
The problem is that the resulting request will not have the expected Content-Length header, but the Transfer-Encoding one. I think the problem is at https://github.com/kennethreitz/requests/blob/master/requests/models.py#L492, where requests sets one header or the other based on the `if length` check. In the case of a stream with 0 length, the check fails and the Transfer-Encoding header gets set.

The snippet above works as intended when the file is non-empty (because the `if length` check passes), and also `requests.put(upload_url, data=uploaded_file.read())` works (as this is not a stream anymore, but it could cause problems when reading a huge file in memory).

**Comment by Lukasa** [comment] 2017-04-20 10:09
Why is the transfer encoding header a problem? HTTP/1.1 servers are required to understand it.

**Comment by CianciuStyles** [comment] 2017-04-20 10:14
The problem is not in the Transfer-Encoding header, but the lack of the Content-Length header: if I try to upload the file to Amazon S3 (for example), it will reply with a 411 Content Length Missing response.

**Comment by Lukasa** [comment] 2017-04-20 10:42
Ok, so this boils down to an S3 behaviour, as S3 requires the content length. 

Requests does not in general consider this behaviour a bug: I consider S3 at fault here. However, it's understandably a problem. You should be able to get the behaviour you want by writing a small proxy object that sends all `read` calls to the Django object and that implements `__len__`, which will be enough for us to work out its length.

**Comment by Lukasa** [comment] 2017-04-20 10:46
Oh I apologise. You're posting an empty file. Requests really does not provide an easy way to override our logic here, which is very deliberate (plenty of users pass us file objects that return a length of zero but which nonetheless return data from `read()`). For this reason the easiest thing to do is likely to use the [PreparedRequest flow](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests) to tweak the headers of the prepared request to suit this case.

**Comment by sigmavirus24** [comment] 2017-04-22 12:45
Thank you for opening this @CianciuStyles. I believe if you follow @Lukasa's advice you'll be able to solve your problem nicely. As a result, I'm closing this since it's not a bug and you now have a suitable workaround. Cheers!

**Closed by sigmavirus24** 2017-04-22 12:45 UTC
