### ISSUE TITLE
"Packages" module is missing in Requests 2.16.0

### ISSUE THREAD

**Issue by velmurugan17** [kennethreitz/requests#4072] opened 2017-05-27 09:22 UTC
Description
We are using requests package for our application development and the framework picks up latest version of requests whenever it builds.Today we noticed that our app broken due to new version of Requests 2.16.0.The "Packages" module is completely missing and it leads to our delivery blocking,Could you please check and let us know if we can expect any quick fix for this issue?

Working version:
2.14.2 and 2.15.1

**Comment by Lukasa** [comment] 2017-05-27 09:29
This is a duplicate of #4069, please check open issues before raising bug reports. This goes double for emailing maintainers directly: it would have taken you 5 seconds to see your issue on the issue tracker.

**Closed by Lukasa** 2017-05-27 09:29 UTC

**Comment by velmurugan17** [comment] 2017-05-27 09:47
Sorry for the duplicate

**Comment by kennethreitz** [comment] 2017-05-27 13:46
2.16.1 released, which fixes this!

**Comment by kennethreitz** [comment] 2017-05-27 14:13
Note: code that was written to import against the requests.packages namespace previously will have to import code that rests at this module-level now.

For example:

    from requests.packages.urllib3.poolmanager import PoolManager

Will need to be re-written to be:

    from requests.packages import urllib3
    urllib3.poolmanager.PoolManager

Or, even better:

    from urllib3.poolmanager import PoolManager

**Comment by kennethreitz** [comment] 2017-05-27 15:08
Requests v2.16.2 is now out, which makes the above code no longer necessary.
