### ISSUE TITLE
2.7.0 Timeout Regression: ValueError: Timeout value connect was (5, 5), but it must be an int or float.

### ISSUE THREAD

**Issue by ez47** [kennethreitz/requests#2723] opened 2015-08-13 22:56 UTC
What happened to specifying a tuple for diffrent read and connect timeouts? 

http://requests.readthedocs.org/en/latest/user/advanced/#timeouts
http://docs.python-requests.org/en/latest/user/advanced/#timeouts

on 2.7.0 it gives this error 
```ValueError: Timeout value connect was (5, 5), but it must be an int or float.```

its getting kinda annoying having to keep dealing with this problem

**Comment by Lukasa** [comment] 2015-08-14 02:47
Can you provide the full trace back please?

**Comment by Lukasa** [comment] 2015-08-31 06:51
I cannot reproduce this and @ez47 is unresponsive, so I'm closing until we can get a repro.

**Closed by Lukasa** 2015-08-31 06:51 UTC

**Comment by ez47** [comment] 2015-09-13 01:08
sorry this was caused by PIP1 that referenced different urllib2, because PIP uses Requests itself, PIP1 has a outdated version of Requests.

**Comment by ueg1990** [comment] 2015-09-13 01:15
+1 for virtualenv/virtualenvwrapper
