### ISSUE TITLE
HEAD request not following redirects since 2.6.1

### ISSUE THREAD

**Issue by markunsworth** [kennethreitz/requests#2575] opened 2015-04-28 14:33 UTC
The following should follow the redirects but it just hangs

    import requests
    requests.head("http://bit.ly/DyE5", allow_redirects=True)

Have tested this on version 2.6.0, 2.6.1 and 2.6.2 and it stopped working at 2.6.1.

Have also tested as a GET request and that works fine on all versions.

**Comment by t-8ch** [comment] 2015-04-28 15:16
_not_ a duplicate of #2568

**Comment by t-8ch** [comment] 2015-04-28 15:25
Most probably a duplicate of shazow/urllib3#601
The server does not do `Transfer-Encoding: chunked` but rather an explicit `Content-Length` without a body following.

**Comment by Lukasa** [comment] 2015-04-28 15:26
@t-8ch This is an odd dupe of shazow/urllib3#601 then, but I suppose it's possible. Definitely seems like the relevant smoking gun for now, so I'm closing to centralise there.

**Closed by Lukasa** 2015-04-28 15:26 UTC

**Comment by t-8ch** [comment] 2015-04-28 15:36
Ha, I was wrong. We survive the brokenness of bit.ly and die in brokenness of google.
Google seems to be generally bad on `HEAD` requests. So it definitely a dupe.

``` py
requests.head("http://www.google.co.uk", allow_redirects=True) # google.com is also broken
```

Curl also breaks.

**Comment by Lukasa** [comment] 2015-04-28 15:37
I don't think Google is wrong, I think we're screwing up, as per shazow/urllib3#601.

**Comment by t-8ch** [comment] 2015-04-28 15:39
But should they then not just do `Content-Length: 0` and not chunked?
After all even curl does not handle it.

**Comment by Lukasa** [comment] 2015-04-28 15:41
Not for HEAD requests. The RFC is clear, HEAD requests never have a body, we shouldn't wait for one.

**Comment by Lukasa** [comment] 2015-04-28 15:41
Are you sure curl doesn't handle it? By default curl won't follow redirects, it needs the -L flag.

**Comment by t-8ch** [comment] 2015-04-28 15:44
@Lukasa ofc you are right :-)

``` sh
$ curl -XHEAD -L google.com
```

It gets another redirect with a content-length and then seems to wait for the body

``` sh
curl -XHEAD www.google.de -Lv
```

Yields no redirect for me and also hangs.

cc @bagder

**Comment by Lukasa** [comment] 2015-04-28 15:53
I once had a chat with @bagder about the -X flag, and in particular about how it doesn't actually change curl's logic. The correct flag to pass curl is -I, and when you do that your first example works:

``` bash
$ curl -I -L google.com
```

**Comment by t-8ch** [comment] 2015-04-28 15:55
Should have read the curl docs :-(
So we are back to shazow/urllib3#601

**Comment by Lukasa** [comment] 2015-04-28 16:00
@t-8ch I'm sure @bagder will tell you you're not the first person to make this mistake, and you won't be the last. ;)

Yeah, that's the bug.

**Comment by bagder** [comment] 2015-04-28 18:35
Yeps. The "misuse" of curl -X is widespread, even if I try to educate and document as much as I can...
