### ISSUE TITLE
session proxies not honored during request

### ISSUE THREAD

**Issue by mbondfusion** [kennethreitz/requests#3197] opened 2016-05-16 17:21 UTC
Using a session object and setting the proxies dictionary does not affect the proxies used during a request.

ex: Still tries to use system proxy.
```
s = requests.Session()
s.proxies = {'http': None, 'https': None}
s.post(url='http://10.0.1.1', json={'test': 'data'})
```

Using proxies during each request works, but it would be great to set them at the session level. Specifically if you potentially have dozens or ".post()" or ".get()" calls throughout your script.

Any thoughts?

**Comment by Lukasa** [comment] 2016-05-16 17:23
Thanks for this! This is a duplicate of #2018.

**Closed by Lukasa** 2016-05-16 17:23 UTC
