### ISSUE TITLE
Unicode decode error with PATCH request

### ISSUE THREAD

**Issue by scossu** [kennethreitz/requests#2938] opened 2015-12-19 05:06 UTC
In requests 2.9.0:

    >>> requests.patch('https://example.org', data=bytes('ô', 'utf-8'))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/combine/virtualenv/lib/python3.4/site-packages/requests/api.py", line 133, in patch
        return request('patch', url,  data=data, **kwargs)
      File "/usr/local/combine/virtualenv/lib/python3.4/site-packages/requests/api.py", line 53, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/combine/virtualenv/lib/python3.4/site-packages/requests/sessions.py", line 454, in request
        prep = self.prepare_request(req)
      File "/usr/local/combine/virtualenv/lib/python3.4/site-packages/requests/sessions.py", line 388, in prepare_request
        hooks=merge_hooks(request.hooks, self.hooks),
      File "/usr/local/combine/virtualenv/lib/python3.4/site-packages/requests/models.py", line 296, in prepare
        self.prepare_body(data, files, json)
      File "/usr/local/combine/virtualenv/lib/python3.4/site-packages/requests/models.py", line 447, in prepare_body
        body = self._encode_params(data)
      File "/usr/local/combine/virtualenv/lib/python3.4/site-packages/requests/models.py", line 84, in _encode_params
        return to_native_string(data)
      File "/usr/local/combine/virtualenv/lib/python3.4/site-packages/requests/utils.py", line 700, in to_native_string
        out = string.decode(encoding)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

This seems to be a problem with all strings containing Unicode characters. It works without problems in 2.8.1.

**Comment by Lukasa** [comment] 2015-12-19 08:39
This is a duplicate of #2933 and #2930, and is fixed in #2931. Thanks for the report, but in future please check both open and **closed** issues before filing a bug, as the issue may already be known. A new release of requests will be made on Monday that contains the fix for this issue.

Thanks! :sparkles: :cake: :sparkles:

**Closed by Lukasa** 2015-12-19 08:39 UTC
