### ISSUE TITLE
[2.14.0] NameError: name 'platform_system' is not defined for pip 6.0.7 

### ISSUE THREAD

**Issue by moylop260** [kennethreitz/requests#4008] opened 2017-05-09 19:02 UTC
Travis use `pip 6.0.7`
Today we had the following error:
```python
pip install -U requests==2.14.0

Using cached requests-2.14.0-py2.py3-none-any.whl
  Exception:
  Traceback (most recent call last):
    File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pip/req/req_set.py", line 436, in prepare_files
      req_to_install.extras):
    File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2496, in requires
      dm = self._dep_map
    File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2697, in _dep_map
      self.__dep_map = self._compute_dependencies()
    File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2730, in _compute_dependencies
      common = frozenset(reqs_for_extra(None))
    File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2727, in reqs_for_extra
      if req.marker_fn(override={'extra':extra}):
    File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pip/_vendor/_markerlib/markers.py", line 113, in marker_fn
      return eval(compiled_marker, environment)
    File "<environment marker>", line 1, in <module>
  NameError: name 'platform_system' is not defined
```

We can fix it using:
`pip install -U pip`
`# Successfully installed pip-9.0.1`

But maybe too much travis build use default pip version
Could be dual compatibility this requests package?

We had a similar fix for pylint: https://github.com/PyCQA/astroid/pull/360 based on https://github.com/pypa/packaging/issues/72

**Comment by Lukasa** [comment] 2017-05-09 19:02
Thanks, this is a duplicate of #4006. See that issue for more discussion.

**Closed by Lukasa** 2017-05-09 19:02 UTC
