### ISSUE TITLE
requests 2.6.1 and 2.6.2 causes ResponseNotReady error for 303 answers

### ISSUE THREAD

**Issue by obormotov** [kennethreitz/requests#2574] opened 2015-04-28 14:05 UTC
now I've got for redirections:
```
  File "bin/eggs/requests-2.6.2-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "bin/eggs/requests-2.6.2-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', ResponseNotReady())
```
requests 2.6 works fine.

**Comment by Lukasa** [comment] 2015-04-28 14:23
This is a duplicate of #2568.

**Closed by Lukasa** 2015-04-28 14:23 UTC
