### ISSUE TITLE
proxy-scheme is case sensitivity or not?

### ISSUE THREAD

**Issue by henry51** [kennethreitz/requests#3074] opened 2016-04-05 01:45 UTC
This question came out when I tried to validate some proxies.
If  proxy-scheme is uppercase as follows, it will return 200. (The host of proxy is not a true one.)
import requests
proxy = {
	'HTTP': 'HTTP://111.1.11.1:8000'
}
r = requests.get('http://www.sina.com',proxies = proxy)
print (r.status_code)

However, if changing 'HTTP' to 'http', it will raise an error about httpconnectionerror.
So, it is confused me that proxy-scheme is case sensitivity or not? Or something went wrong about my code ?

Hoping to receive your instruction.

**Comment by Lukasa** [comment] 2016-04-05 09:10
Thanks for this!

This is a real bug, but it's a duplicate of #3075. Please see shazow/urllib3#833 to track work on this problem.

**Closed by Lukasa** 2016-04-05 09:10 UTC
