### ISSUE TITLE
Basic Auth broken when username / password is None

### ISSUE THREAD

**Issue by kirichkov** [kennethreitz/requests#3750] opened 2016-12-05 14:15 UTC
It appears commit 329a5cfdd4500fb1ce405a3242ef95f9197d24ba has broken `_basic_auth_str` and it now throws an exception `TypeError` (see below) when the supplied username and password is `None`.

Befor this commit, in requests 2.1.1, it was possible to supply None values for username and password when authentication is optional - in this particular case Home Assistant writing to InfluxDB with default configuration.

Exception thrown:
```python
TypeError: sequence item 0: expected a bytes-like object, NoneType found
```

**Comment by sigmavirus24** [comment] 2016-12-05 14:24
This is a duplicate of #3736

**Comment by sigmavirus24** [comment] 2016-12-05 14:25
In the future, please search closed and open issues before creating new ones that are duplicates.

**Closed by sigmavirus24** 2016-12-05 14:24 UTC

**Comment by kirichkov** [comment] 2016-12-05 14:26
Sorry. I looked at the open tickets only!
