### ISSUE TITLE
Allow a "url_prefix" to be set on Session

### ISSUE THREAD

**Issue by fiatjaf** [kennethreitz/requests#2445] opened 2015-02-12 19:08 UTC
So we can do something like this:

```python
COUCHDB_URL = 'https://mybigusername:myenourmouspassword@mycouchdb.provider.com/databasename/'

s = requests.Session(url_prefix=COUCHDB_URL)
r = s.get('/_all_docs', params=dict(include_docs=True))
r = s.get('/some_document_id')
```

The example uses the CouchDB API and it would almost entirely prevent the need for API wrappers like [this](https://github.com/adamlofts/couchdb-requests) (see it storing the url prefix [right here](https://github.com/adamlofts/couchdb-requests/blob/93e83d5e8cf7b0894de33747572789777dee845e/couchdbreq/resource.py#L80)). But extensive usage of any REST API would benefit from this.

**Comment by sigmavirus24** [comment] 2015-02-12 19:13
Duplicate of #133.

In short, we're not adding new features to the API and we're especially not going to attempt to build URLs for you when you're using a session. There are lots of other libraries that allow for similar functionality but that is not something inherently necessary in the transmission or handling of HTTP. It's important to keep in mind that `requests` is "HTTP for Humans", not "HTTP and a bunch of super nice to have features for Humans". The main focus of this library is HTTP.

**Closed by sigmavirus24** 2015-02-12 19:13 UTC

**Comment by fiatjaf** [comment] 2015-02-12 19:48
Well, thank you.
