### ISSUE TITLE
Cannot clone repo due to bad timezone error

### ISSUE THREAD

**Issue by nyuszika7h** [kennethreitz/requests#3805] opened 2017-01-10 12:34 UTC
```
nyuszika7h@cadoth ~/src > git clone https://github.com/kennethreitz/requests.git
Cloning into 'requests'...
remote: Counting objects: 18867, done.
remote: Compressing objects: 100% (11/11), done.
error: object 5e6ecdad9f69b1ff789a17733b8edc6fd7091bd8: badTimezone: invalid author/committer line - bad time zone
fatal: Error in object
fatal: index-pack failed
```

**Comment by Lukasa** [comment] 2017-01-10 12:35
Thanks for raising this issue! In future, please search the issue history before opening new issues on projects, as you'll often find that your issue has been reported before. In this case, this is a duplicate of #3088, #3008, and #2690.

**Comment by ghost** [comment] 2017-01-10 12:36
Sorry. I did search, but didn't get the right terms.

**Closed by Lukasa** 2017-01-10 12:35 UTC

**Comment by Lukasa** [comment] 2017-01-10 12:37
If you have an error message, it's usually sufficient just to try to search for that. In this case, I searched for "fatal: index-pack failed" and #3088 popped right up.

**Comment by ghost** [comment] 2017-01-10 12:39
Yeah, well, I searched for "timezone" because I didn't realize there's a space in it in the error message. (Also, it's strange, I don't remember enabling fsck, but I found it in my git config.)

**Comment by Lukasa** [comment] 2017-01-10 12:40
fsck is on-by-default on new installs of git, so unless you're persisting a gitconfig from an older version of git you'll always find it on. =)

**Comment by ghost** [comment] 2017-01-10 12:44
I do have a custom gitconfig, so that's strange. This kind of issue could have been avoided if they enabled fsck by default in the first place, but oh well. You can't rewrite 6 years of history now, that would just mess things up even more. I do wonder how that weird timezone ended up in a commit though.

**Comment by Lukasa** [comment] 2017-01-10 12:45
Yeah, it's really annoying because it causes legitimate problems for lots of people, especially those who use git in automated scripts, but we really can't do anything about it now. =(

**Comment by vermeeren** [comment] 2018-09-20 21:13
Even though it hurts to do this, you may want to consider rewriting the history to fix this problem once and for all. For Breathe I ended up doing this and I added a notice to the top of the README, in the biggest heading possible, for a while.

Projects using this as a submodule will have to update the SHA once. But currently many setups encounter a clone failure meaning existing submodules will not work at all and cloning this repo directly won't either.

Ref: https://github.com/michaeljones/breathe/issues/340#issuecomment-394396673
