### ISSUE TITLE
malformed request block

### ISSUE THREAD

**Issue by persiaAziz** [kennethreitz/requests#3638] opened 2016-10-25 18:08 UTC
specifying both Content-Length and transfer-encoding in the header dictionary creates malformed request block. I think it should throw an exception and abort the request

**Comment by Lukasa** [comment] 2016-10-25 18:13
I'm going to close this in favour of #3637.

**Closed by Lukasa** 2016-10-25 18:13 UTC

**Comment by persiaAziz-zz** [comment] 2016-10-25 20:44
This is a different issue by the way . Code to reproduce:

`
import gevent
import socket
import requests
import os
from threading import Thread
import sys
bSTOP = False
def handleResponse(response,_args, *_kwargs):
    print(response.status_code)

def gen():
    yield 'pforpersia,champaignurbana'.encode('utf-8')
    yield 'there'.encode('utf-8')

def txn_replay():
    try:
        request_session = requests.Session()
        hostname = "127.0.0.1"
        port = "8080"
        request_session.proxies =  {"http": "http://{0}:{1}".format(hostname, port)}
        hdr = {'Host':'www.blabla.com','content-type': 'application/json', 'Content-Length':'20' 
, 'Content-MD5':'5f4308e950ab4d7188e96ddf740855ec', 'Transfer-Encoding':'Chunked'}
#, 'Content-Length':'20'
        body=gen()
        response = request_session.get('http://blabla.com/blabla', headers=hdr, stream=True, data=body)
    except UnicodeEncodeError as e:
        print("UnicodeEncodeError exception")

```
except requests.exceptions.ContentDecodingError as e:
    print("ContentDecodingError",e)
except:
    e=sys.exc_info()
    print("ERROR in requests: ",e)
```

def main():
    txn_replay()

if **name** == '**main**':
    main()
`

**Comment by persiaAziz-zz** [comment] 2016-10-25 20:45
**wireshark**

`GET http://blabla.com/blabla HTTP/1.1
Accept: _/_
Connection: keep-alive
User-Agent: python-requests/2.10.0
Accept-Encoding: gzip, deflate
content-type: application/json
Content-Length: 20
Host: www.blabla.com
Content-MD5: 5f4308e950ab4d7188e96ddf740855ec
Transfer-Encoding: chunked

pforpersia,champaignurbanatherethere

HTTP/1.1 502 Success
Date: Tue, 25 Oct 2016 20:41:08 GMT
Connection: close
Server: ATS/7.1.0
Cache-Control: no-store
Content-Type: text/html
Content-Language: en
Content-Length: 247`

**Comment by persiaAziz-zz** [comment] 2016-10-25 20:47
The problem is that Session generates the request block which is basically malformed with transfer-encoding and content-length being specified and adding message body. This should either take the content-length field out or raise an exception

**Comment by Lukasa** [comment] 2016-10-25 20:57
This behaviour has been known about Requests for a long time and is intentional. Requests basically totally disregards the user-set headers that have anything to do with request framing (content-length or transfer-encoding). You must not set them.
