### ISSUE TITLE
Bad default parameters to iter_content

### ISSUE THREAD

**Issue by gibiansky** [kennethreitz/requests#2854] opened 2015-10-29 16:20 UTC
Apologies if this is a duplicate or not a bug – I ran into this recently and figured I should report it.

`iter_content` takes a `chunk_size` argument, which defaults to 1. Various code snippets on the internet call `request.iter_content()`. This is incredibly inefficient, because it is using a buffer size of 1 *byte*. I think `requests` should either a) set `chunk_size` to something more reasonable, like 2048 or 4096, or b) make `chunk_size` a required argument. (Solution a is more palatable since it's backwards compatible.)

**Comment by sigmavirus24** [comment] 2015-10-29 16:48
See https://github.com/kennethreitz/requests/issues/844 please

**Comment by Lukasa** [comment] 2015-10-29 22:03
Yeah, this is an outstanding problem that we haven't gotten around to resolving yet. However, it's a dupe of #844.

**Closed by Lukasa** 2015-10-29 22:03 UTC
