### ISSUE TITLE
Failure while formatting an error for incorrect SSL CA file

### ISSUE THREAD

**Issue by traut** [kennethreitz/requests#2886] opened 2015-11-17 15:13 UTC
Requests fail while trying to format exception related to non-existent CA file.

Code to reproduce:

```
import requests
requests.get('https://google.com', verify='/some/some')
```

results in:

```
  File "/Users/traut/.p/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/Users/traut/.p/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 348, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/Users/traut/.p/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 318, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```

Versions:
Python 2.7.10
Requests 2.8.1

**Comment by sigmavirus24** [comment] 2015-11-17 15:21
This is definitely a duplicate but I don't have the time to find the exact bug right now. The fix is already merged in urllib3 iirc but @Lukasa can correct me.

**Comment by Lukasa** [comment] 2015-11-17 15:24
Yup, this is a duplicate of shazow/urllib3#556.

**Closed by Lukasa** 2015-11-17 15:24 UTC

**Comment by traut** [comment] 2015-11-17 15:25
cool. thanks for looking into it
