### ISSUE TITLE
2.11.1: Using OrderedDict to order headers on session doesn't allow new headers to be added during later request:s

### ISSUE THREAD

**Issue by phrozetime** [kennethreitz/requests#3524] opened 2016-08-18 18:19 UTC
For kicks I decided to order my headers.  According to the directions http://docs.python-requests.org/en/master/user/advanced/ here I just constructed a OrderedDict and set the session.headers value to it.  Now when I use the session for requests e.g. session.get("site", headers={"Referer": "test"}) and try to add a new header is doesn't take.  Only if the header value already exists can it be overriden.  According to the documentation it should be merged.

**Comment by Lukasa** [comment] 2016-08-18 23:18
I can't reproduce this. Can you please provide some sample code? Here is mine:

``` python
>>> import requests
>>> requests.__version__
'2.11.0'
>>> import collections
>>> s = requests.Session()
>>> s.headers = collections.OrderedDict()
>>> s.headers['X-Custom-Whatever'] = 'val'
>>> r = s.get('http://http2bin.org/get', headers={'Custom-Key': 'Custom-Value'})
>>> print r.text
{
  "args": {}, 
  "headers": {
    "Accept-Encoding": "identity", 
    "Connection": "keep-alive", 
    "Custom-Key": "Custom-Value", 
    "Host": "http2bin.org", 
    "Via": "1.1 http2bin.org", 
    "X-Custom-Whatever": "val"
  }, 
  "origin": "24.185.108.14", 
  "url": "http://http2bin.org/get"
}
>>> r.request.headers
{'Custom-Key': 'Custom-Value', 'X-Custom-Whatever': 'val'}
```

**Comment by clesiemo3** [comment] 2016-08-27 02:34
Seems to work for me as well for what it is worth. Python 3.5.2, requests 2.11.1, OSX El Captian 10.11.6

``` python
Python 3.5.2 (default, Jul 28 2016, 21:28:00)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.__version__
'2.11.1'
>>> import collections
>>> s = requests.Session()
>>> s.headers = collections.OrderedDict()
>>> s.headers['X-Custom-Whatever'] = 'val'
>>> r = s.get('http://http2bin.org/get', headers= {'Custom-Key':'Custom-Val'})
>>> print(r.text)
{
  "args": {},
  "headers": {
    "Accept-Encoding": "identity",
    "Connection": "keep-alive",
    "Custom-Key": "Custom-Val",
    "Host": "http2bin.org",
    "Via": "1.1 http2bin.org",
    "X-Custom-Whatever": "val"
  },
  "origin": "24.107.123.117",
  "url": "http://http2bin.org/get"
}

>>> r.request.headers
{'X-Custom-Whatever': 'val', 'Custom-Key': 'Custom-Val'}
```

**Comment by sigmavirus24** [comment] 2016-08-27 11:40
Since @phrozetime hasn't responded and we have multiple people unable to reproduce it. I'm closing this until we have more details.

**Closed by sigmavirus24** 2016-08-27 11:40 UTC
