### ISSUE TITLE
UnicodeDecodeError installing via pip-3.2

### ISSUE THREAD

**Issue by TFenby** [kennethreitz/requests#2419] opened 2015-01-21 15:32 UTC
So here's a weird one. I have a Docker container based on debian:stable where I install python3 and python3-pip, and when trying to install requests from a requirements.txt file I get the following:
```
Downloading/unpacking requests (from -r /tmp/requirements/xxx.txt (line 2))
  Running setup.py egg_info for package requests

Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1014, in prepare_files
    req_to_install.assert_source_matches_version()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 359, in assert_source_matches_version
    version = self.installed_version
  File "/usr/lib/python3/dist-packages/pip/req.py", line 351, in installed_version
    return self.pkg_info()['version']
  File "/usr/lib/python3/dist-packages/pip/req.py", line 318, in pkg_info
    data = self.egg_info_data('PKG-INFO')
  File "/usr/lib/python3/dist-packages/pip/req.py", line 261, in egg_info_data
    data = fp.read()
  File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8161: ordinal not in range(128)
```

However, when I run ```pip-3.2 install requests``` directly, it works fine.
I honestly have no idea where even to start on debugging this.

**Comment by sigmavirus24** [comment] 2015-01-21 17:40
This is a duplicate of an old error that was fixed. Can you confirm that the version of requests is pinned to something in the 2.x line but is not 2.5.1?

**Comment by sigmavirus24** [comment] 2015-01-21 17:41
#2196 is the already fixed issue for reference.

**Comment by TFenby** [comment] 2015-01-21 18:08
I've tried it with no version pinned, pinned to 2.5.1, and pinned to 2.5.0.
The thing that I don't understand is why it only fails when installing from a requirements.txt file.

**Closed** 2015-05-03 15:08 UTC
