### ISSUE TITLE
Broken pipe Exception

### ISSUE THREAD

**Issue by cloverstd** [kennethreitz/requests#2422] opened 2015-01-23 14:03 UTC
I post a large file to server, and it raise `ConnectionError` exception.

```
Traceback (most recent call last):
  File "/Users/cloverstd/.virtualenvs/enterprise/lib/python2.7/site-packages/rq/worker.py", line 479, in perform_job
    rv = job.perform()
  File "/Users/cloverstd/.virtualenvs/enterprise/lib/python2.7/site-packages/rq/job.py", line 466, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "./jobs/office.py", line 97, in notice_file
    open('test.pdf', 'rb')))
  File "/Users/cloverstd/Dropbox/WorkSpace/gench/enterprise/wechatpy/enterprise/client/api/media.py", line 15, in upload
    'media': media_file
  File "/Users/cloverstd/Dropbox/WorkSpace/gench/enterprise/wechatpy/client/api/base.py", line 20, in _post
    return self._client._post(url, **kwargs)
  File "/Users/cloverstd/Dropbox/WorkSpace/gench/enterprise/wechatpy/client/base.py", line 74, in _post
    **kwargs
  File "/Users/cloverstd/Dropbox/WorkSpace/gench/enterprise/wechatpy/client/base.py", line 39, in _request
    **kwargs
  File "/Users/cloverstd/.virtualenvs/enterprise/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/cloverstd/.virtualenvs/enterprise/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/cloverstd/.virtualenvs/enterprise/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/cloverstd/.virtualenvs/enterprise/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))
```

The `test.pdf` is 4.2M, when I post it as a file, I get ConnectionError Exception.
But I use curl to post it to server, it can be uploaded successful.

**Comment by kevinburke** [comment] 2015-01-23 15:48
Can you reproduce it every time? What curl command are you using? Does the
server have any useful log messages?

## 

Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by sigmavirus24** [comment] 2015-01-23 16:03
Have you tried without using `rq`? Are you using curl within `rq`?

**Comment by barseghyanartur** [comment] 2015-03-22 21:59
Same here. I'm using requests to post large files (about 8 Mb in total) to a Django endpoint. Getting same error. It does work fine with smaller files.

**Comment by sigmavirus24** [comment] 2015-03-23 00:32
@barseghyanartur perhaps you can give us more details than @cloverstd did, for example, what code will reproduce this?

I have a suspicion as to the cause but I haven't been able to reproduce this yet.

**Comment by barseghyanartur** [comment] 2015-03-23 01:10
@sigmavirus24 

I have gone a bit further in research and this is what I have found.

Basically, it's this:

```
requests.post(some_url, data=data_dict, files=files_dict)
```

Environment details:
- Python==2.7.3
- requests==2.5.1

I managed to reproduce the problem exactly. In my case, the endpoint is a multi-lingual Django site. Requests to URL without the language prefix (like "http://example.com/foo/endpoint/") do get redirected to the same URL with the language prefix (like "http://example.com/en/foo/endpoint/").

If `some_url` is "http://example.com/foo/endpoint/" I get an error:

('Connection aborted.', error(32, 'Broken pipe'))

If `some_url` is "http://example.com/en/foo/endpoint/" it all goes fine. Likely, `requests` doesn't handle large post requests to endpoints which do redirect them to some other endpoints.

I have just tried it with requests==2.6.0 and I do get the same problem.

**Comment by sigmavirus24** [comment] 2015-03-23 01:18
@barseghyanartur can you give us the status code from the redirect?

**Comment by Lukasa** [comment] 2015-03-23 06:17
I wonder if the remote end isn't expecting a body but we're sending it anyway, so we get our connection torn down.

**Comment by sigmavirus24** [comment] 2015-03-23 14:39
@Lukasa or if we change the method (i.e., in a case like 7231 Section 6.6.4) without stripping the body/content-length. (or strip the body and not the content-length).

**Comment by sigmavirus24** [comment] 2015-03-23 14:39
Really any information @barseghyanartur can give us about the redirect response and the subsequent request will be helpful

**Comment by barseghyanartur** [comment] 2015-03-23 15:03
@sigmavirus24 

Hey, thanks for getting back on this. I'll post it here quite soon after I get home. :) That's gonna be in about 5 hours.

**Comment by sigmavirus24** [comment] 2015-03-23 15:14
@barseghyanartur no rush. I'd like to fix this once and for all. That can be today or next week. As long as it's fixed, I'll be happy.

**Comment by barseghyanartur** [comment] 2015-03-24 22:13
@sigmavirus24 

I don't get any response back, since it fails hard.

``` py
Traceback (most recent call last):
  File "requests_test.py", line 29, in <module>
    response = requests.post(url, data=data, files=files)
  File "/home/me/.virtualenvs/env/local/lib/python2.7/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/me/.virtualenvs/env/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/me/.virtualenvs/env/local/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/me/.virtualenvs/env/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/me/.virtualenvs/env/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))
```

And this is the code:

``` py
import os

import requests

url = 'http://localhost:8001/foo/endpoint/'

data = dict(['input_{0}'.format(index), 'some value {0}'.format(index)] for index in range(10))

FILES = (
    '/home/me/bbrepos/requests_test/media/1.gif',
    '/home/me/bbrepos/requests_test/media/2.gif',
)

files = dict(['file_{0}'.format(index), (os.path.basename(file_path), open(file_path, 'rb'))] for index, file_path in enumerate(FILES))

response = requests.post(url, data=data, files=files)
```

**Comment by sigmavirus24** [comment] 2015-03-25 16:52
@barseghyanartur you can determine what the redirect codes, etc. are with `requests.post(url, data=data, files=files, allow_redirects=False)`

**Comment by barseghyanartur** [comment] 2015-03-25 16:58
@sigmavirus24 

Ah, sorry, I didn't realise you were asking for that. It was 301, as far as I remember.

**Comment by Lukasa** [comment] 2015-03-25 18:13
Given that this is all plaintext, you should be able to get a packet capture of the whole transaction. Running `tcpdump -nnvvXSs 1514 port 8001 and host localhost` should do the trick.

**Comment by JazzFan** [comment] 2015-04-07 21:05
I'm having the same problem:  small (1MB) data works, but large (50MB) data breaks ('Connection aborted.', error(32, 'Broken pipe')).   

The complications in my case are that (1) I don't control the Web service -- it's the property of another company; (2) the protocol is HTTPS, but perhaps the packet capture would still be informative, even if the payload data is encrypted from tcpdump's point of view.

I will get a packet capture of a broken large transaction and reply back.

**Comment by JazzFan** [comment] 2015-04-07 22:51
I created the tcpdump file https://gist.github.com/JazzFan/fc55e28c525518ada71f with this command:
    `sudo tcpdump -nnvvXSs 1514 port 443 and host 54.200.58.94`

My program ran under Python 2.7.8, with `requests` 2.5.3 (but I feel pretty confident that I can get it to break under other versions of Python or `requests`, if you would prefer others).

The relevant lines of the Python program:

```
    import requests
    ...
    headers = {'Content-Type':  'application/json'}
    response = requests.post(URL, data=wrapped_chunk, headers=headers)
```

The idea of the program is to split a large file into 50MB chunks, wrap each chunk with a bit of JSON, then POST it to the Web service API that a vendor company provides to my company.

The stack trace (home dir redacted with `~`)

```
Traceback (most recent call last):
  File "~/bin/progname.py", line 399, in <module>
    main()
  File "~/bin/single_process.py", line 33, in _
    return f(*a, **kw)
  File "~/bin/progname.py", line 392, in main
    max_return_code = send_file_chunks(fn, api_key, args.parallelism)
  File "~/bin/progname.py", line 347, in send_file_chunks
    chunk_filenames))
  File "~/anaconda/envs/py278/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "~/anaconda/envs/py278/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))
```

I realize the stack trace has everything but `requests` in it; let me know if that's a problem and I'll write a simpler program in order to get a clean stack trace.

**Comment by sigmavirus24** [comment] 2015-04-07 23:31
@jazzfan thanks for doing that. I'll look tonight and I suspect that @Lukasa will look when he wakes up

**Comment by Lukasa** [comment] 2015-04-08 00:24
@sigmavirus24 You forget that I am in NYC at the minute, and so am (relatively) awake!

As I've said elsewhere, EPIPE almost always comes when we attempt to send on a connection that has been remote-closed.

I think it would be most interesting if you could run a patch in requests' vendored copy of urllib3 that would throw the socket object up with the `ConnectionError`, and then read from it. The exact patch to apply here is a bit unclear and overlaps with some other stuff we've been thinking about when it comes to EPIPE.

Alternatively, a non-SSL repro would work!

**Comment by JazzFan** [comment] 2015-04-08 00:39
@Lukasa, does this mean that the SSL tcpdump file is essentially useless?  Also, I'm afraid I'm too much of a newbie to be able to figure this patch you're describing, especially if it's unclear to you.  

I guess I'll rig up some kind of little test HTTP server on my localhost and see if I can reproduce the error using that.

**Comment by Lukasa** [comment] 2015-04-08 00:56
@JazzFan Sadly, it's not very easy to tell from it whether or not a response was sent. That said, we can definitely see that the remote end tore the connection down at 15:17:24.141410 (sending a TCP FIN). Shortly thereafter we emitted another packet, which caused the remote end to send a barrage of TCP RSTs (though most of these appear to be retransmits, and in practice appear to be in response to the other TCP packets that were in flight when the FIN was emitted (as shown by the sequence/acknowledgement numbers).

What we really want to understand is what triggered the connection teardown.

**Comment by barseghyanartur** [comment] 2015-04-08 06:50
@Lukasa 

Well, one thing is clear - it happens only when large amounts of data (files) and transferred.

**Comment by Lukasa** [comment] 2015-04-08 12:17
@barseghyanartur Yup, but that doesn't necessarily mean much. You can only get an EPIPE if the remote end forcibly closes the connection, which is only likely to happen for large data files.

**Comment by barseghyanartur** [comment] 2015-04-08 12:24
@Lukasa 

Are you interested to know what happens if 20 Mb plain text (textarea) is posted?

**Comment by Lukasa** [comment] 2015-04-08 12:54
I'm really interested in seeing something happening here in plaintext. =D

**Comment by JazzFan** [comment] 2015-04-09 03:01
Well, for whatever reason I just can't get tcpdump to actually capture the packets.  I get output like this:

```
0 packets captured
303 packets received by filter
0 packets dropped by kernel
```

But this example breaks for me, again with Python 2.7.8 and requests 2.5.3:

```
#!/usr/bin/env python

import requests

line = '.' * 79 + '\n'
data = line * 10000000
response = requests.post('http://127.0.0.1:8000', data=data)
print(response)
```

Here is the stack trace (again with home dir redacted as `~`):

```
$ ./requests_test.py 
Traceback (most recent call last):
  File "./requests_test.py", line 7, in <module>
    response = requests.post('http://127.0.0.1:8000', data=data)
  File "~/anaconda/envs/py278/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "~/anaconda/envs/py278/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "~/anaconda/envs/py278/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "~/anaconda/envs/py278/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "~/anaconda/envs/py278/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))
```

I can capture the packets with Wireshark.  I know that you're looking for a particular kind of plaintext output from tcpdump, but would you happen to know how to get the equivalent plaintext output from Wireshark?  
On the off chance that it would work for you, I've created a gist, wireshark.txt, https://gist.github.com/JazzFan/8517983ff5eed2d95b10.

**Comment by Lukasa** [comment] 2015-04-09 11:04
@JazzFan In addition to what you sent me I need the actual packet data. There's a 40-byte TCP payload coming from your server in frame 60 that Wireshark is claiming is HTTP data, but it hasn't broken out the data itself so I can't see it.

What tcpdump command are you running?

**Comment by JazzFan** [comment] 2015-04-09 13:46
I'm running

```
sudo tcpdump -nnvvXSs 1514 port 8000 and host 127.0.0.1 > tcpdump.txt
```

and variations on that (e.g., omitting the `and host 127.0.0.1`).  After triggering the bug in another window and hitting `Ctrl-C` on the `tcpdump` command, I get something like

```
0 packets captured
492 packets received by filter
0 packets dropped by kernel
```

and an empty tcpdump.txt file.  I interpret the output to mean that the filter saw the packets but didn't capture them, but I don't know why it didn't capture them.

**Comment by JazzFan** [comment] 2015-04-09 13:53
Also, FWIW, the 40 bytes of TCP data payload on packet 60 are

```
<html><body><h1>POST!</h1></body></html>
```

This is just the standard response that my dummy HTTP server makes to any post request.   FWIW, here is my HTTP server:

``` python
#!/usr/bin/env python
"""

Very simple HTTP server in python.

Usage::
    ./dummy-web-server.py [<port>]

Send a GET request::
    curl http://localhost

Send a HEAD request::
    curl -I http://localhost

Send a POST request::
    curl -d "foo=bar&bin=baz" http://localhost

"""
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
import SocketServer


class S(BaseHTTPRequestHandler):
    def _set_headers(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_GET(self):
        self._set_headers()
        self.wfile.write("<html><body><h1>hi!</h1></body></html>")

    def do_HEAD(self):
        self._set_headers()

    def do_POST(self):
        # Doesn't do anything with posted data
        self._set_headers()
        self.wfile.write("<html><body><h1>POST!</h1></body></html>")


def run(server_class=HTTPServer, handler_class=S, port=8000):
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    print 'Starting httpd...'
    httpd.serve_forever()


if __name__ == "__main__":
    from sys import argv

    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()
```

**Comment by JazzFan** [comment] 2015-04-09 16:08
Oops, I forgot to include @Lukasa in my previous comments.

**Comment by Lukasa** [comment] 2015-04-10 20:19
@JazzFan I haven't tested this yet (I'm at PyCon so I'm short on time), but my suspicion is that your test server causes this by immediately writing a response and then going out of scope without draining the POST data. This means that the server will attempt to close the socket, sending a TCP FIN, and then causing the Broken Pipe error.

**Comment by JazzFan** [comment] 2015-04-11 02:09
@Lukasa, please don't let me take you away from PyCon!

I think you are right about needing to drain the POST data.  When I change my test server's `do_POST` method from this:

```
    def do_POST(self):
        self._set_headers()
        self.wfile.write("<html><body><h1>POST!</h1></body></html>")
```

to this, by adding code to read all of the input stream for this post request:

```
    def do_POST(self):
        length = int(self.headers["Content-Length"])
        self.rfile.read(length)   # make sure to drain the POST data
        self._set_headers()
        self.wfile.write("<html><body><h1>POST!</h1></body></html>")
```

then the error goes away; `requests` does not terminate in a stack trace.  

So based on my evidence, when `requests` abnormally terminates, it is due to a problem in the server implementation, not in `requests` itself.  Maybe other people have evidence that it's a problem in `requests`, but on the face of it, I don't.   Sorry to have troubled you!

**Comment by Lukasa** [comment] 2015-04-11 02:58
No problem @JazzFan! I think we still would like to surface responses in this case, but it's another issue.

**Closed by Lukasa** 2015-04-11 02:58 UTC
Labels: Needs Info

**Comment by sirlark** [comment] 2015-07-21 12:37
Hi, I realise this is closed, but I'm having a similar issue, also with a Flask server. I'm sending a JSON GET request to a flask route that only accepts POST requests. Flask returns immediately with a 403 (Bad Method), but if the request data is large (7Mb in my case), requests keeps trying to push data until the request is fully sent. I'm not doing a file upload.

I realise that there has been a broken pipe, but at the same time there has also been been a 405 response. Wouldn't it be better to return the 405 in this case, since it implies the request was finished, even if the pipe closed prematurely?

**Comment by Lukasa** [comment] 2015-07-21 13:01
> Wouldn't it be better to return the 405 in this case, since it implies the request was finished, even if the pipe closed prematurely?

Yes. What we don't know is whether we _can_. We haven't had anyone sit down to work out if httplib will let us do the right thing here.

**Comment by sirlark** [comment] 2015-07-21 13:07
Okay, I'm happy to do this, just let me know how. I at least have control of the server and the client in this case, but if you need tcp dumps, I'll need no anonymise the test data (It's health stuff)

**Comment by Lukasa** [comment] 2015-07-21 13:13
You'll need to familiarise yourself with httplib in order to make the troublesome request, and then see if you can still meaningfully receive the response.

**Comment by sirlark** [comment] 2015-07-21 13:24
What sort of level am I looking at here? Am I using httplib.socket.create_connection, or httplib.HTTPConnection?

**Comment by Lukasa** [comment] 2015-07-21 13:29
`HTTPConnection` is fine. =)

**Comment by sirlark** [comment] 2015-07-21 13:43
Hmm, this doesn't look positive. It looks like the httplib.HTTPConnection object raises the exception, and doesn't return a response object. 

Client code:

```
$ python
Python 2.7.10 (default, May 30 2015, 12:53:33) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import httplib
>>> conn = httplib.HTTPConnection("localhost", 8080)
>>> R = conn.request("GET", "http://localhost:8080/MyService/", open("example-input.json", "r"), {"Content-Type": "application/json", "Accept": "application/json"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 866, in send
    self.sock.sendall(datablock)
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe
>>> 
```

Server output:

```
127.0.0.1 - - [21/Jul/2015 15:36:25] "GET http://localhost:8080/SleepModel/ HTTP/1.1" 405 -
```

**Comment by Lukasa** [comment] 2015-07-21 13:47
I know that. What I want you to do is follow-up from that with `conn.getresponse()` and see what happens.

**Comment by sirlark** [comment] 2015-07-21 13:59
Oh right, yup it works,

```
>>> new_R = conn.getresponse()
>>> new_R.status
405
```

**Comment by Lukasa** [comment] 2015-07-21 14:00
Ok, so _in principle_ there are certain kinds of exceptions we can still get responses from. I think I floated the idea that we could attach them to the thrown exception for BrokenPipe. I think we'd have to do that from urllib3 though.

**Comment by sjagoe** [comment] 2015-07-30 15:57
@Lukasa I am seeing a similar issue, but the cause is from nginx immediately returning a `413 Request Entity Too Large`. RFC2616 says this about 413:

> The server _MAY close the connection_ to prevent the client from continuing the request. 

The server closing the connection is the behaviour I am seeing, and requests (actually, I think the issue is in Python's `httplib`) is not handling that case.

I have a server on EC2 that can be used for testing against. nginx is configured with a `max_client_body_size` of `1k`, and the Python server behind nginx is the example posted above in this issue (with the modification to consume the whole body). The catch is that nginx doesn't proxy the request to the Python server due to the `413` error. You can POST to `http://52.18.181.108/`.
In my case, when uploading a file larger than roughly 75MB I see this issue.

Using wireshark, I see the below behaviour, where nginx responds upfront with a 413, but Python httplib doesn't handle the response until the very end of the request (happily uploading the whole file while the server has already rejected the request). If the file is large enough, nginx will terminate the connection before httplib/urllib3 handles the response, resulting in either a `Broken Pipe`, or a `Connection reset by peer`.

```
No.     Time        Source          Dest.           Proto.  Size    Info.
41      4.584020000 172.17.5.1      52.18.181.108   HTTP    1359    POST / HTTP/1.1 
42      4.601824000 52.18.181.108   172.17.5.1      TCP     66      80→34354 [ACK] Seq=1 Ack=194 Win=28032 Len=0 TSval=26477364 TSecr=102696248
43      4.602120000 52.18.181.108   172.17.5.1      HTTP    446     HTTP/1.1 413 Request Entity Too Large  (text/html)
44      4.602191000 172.17.5.1      52.18.181.108   TCP     66      34354→80 [ACK] Seq=1487 Ack=381 Win=30336 Len=0 TSval=102696269 TSecr=26477364
45      4.602875000 172.17.5.1      52.18.181.108   TCP     66      34354→80 [FIN, ACK] Seq=1487 Ack=381 Win=30336 Len=0 TSval=102696269 TSecr=26477364
...
continues
...
72838   33.67479600 52.18.181.108   172.17.5.1      TCP     66      80→34355 [RST, ACK] Seq=381 Ack=70189102 Win=547840 Len=0 TSval=26484632 TSecr=102725309
72839   33.67581600 52.18.181.108   172.17.5.1      TCP     54      80→34355 [RST] Seq=381 Win=0 Len=0
```

cc @cournape

**Comment by Lukasa** [comment] 2015-07-30 16:37
Yeah, as I've said, I think we can do the right thing here in some situations, but I'd want to test a lot of edge cases to confirm we don't get stuck in situations that _aren't_ like this one.

**Comment by sjagoe** [comment] 2015-07-30 16:41
I think that (in my case, at least) there is an underlying issue in httplib where it is just not possible to end a request at the time when the server has sent an error response. The client _always_ tries to send the whole body. So I think while you may be able to give the user a better error (i.e. what the server actually sent), the overall user experience will still be worse than expected unless you override the `httplib.HTTPConnection.send()` method to handle the server response as soon as it is received. Although that seems to have pretty severe consequences for the whole design of `httplib`.

**Comment by Lukasa** [comment] 2015-07-30 16:44
Yeah, you're absolutely right on that front. This will always be sub-par, but I think that's ok: raising an exception in this case is probably the right thing to do.

**Comment by E3V3A** [comment] 2016-02-15 00:43
@sjagoe Thanks for this info! 

> Using wireshark, I see the below behaviour, where nginx responds upfront with a 413, but Python httplib doesn't handle the response until the very end of the request (happily uploading the whole file while the server has already rejected the request). If the file is large enough, nginx will terminate the connection before httplib/urllib3 handles the response, resulting in either a `Broken Pipe`, or a `Connection reset by peer`.

This indeed seem to be the case. 

I have the same exact trouble for a completely different server (VirusTotal). The easy way to check this behavior is by creating a file slightly bigger than 64Mib and another slightly smaller with:

``` bash
# Create a 64 MiB file:
$ dd if=/dev/urandom of=zzzz.txt bs=1048576 count=64
...
67108864 bytes (67 MB) copied, 0.182048 s, 369 MB/s
```

Submitting this gives the `(104, 'ECONNRESET')` exception, indicating that the foreign server dropped the connection. (This happens fast.)

The smaller file was created with:

``` bash
$ dd if=/dev/urandom of=zzzz.txt bs=1048576 count=63
...
66060288 bytes (66 MB) copied, 0.184529 s, 358 MB/s
```

Indeed results in the correct server response of `413`, exceeding the 32 MB API limit. (This process is slow.)

What is weird is the speed of the returned result, which is opposite of what is expected.

**Comment by chenziliang** [comment] 2016-06-29 10:48
May i ask if there is a resolution for this issue ?

**Comment by Lukasa** [comment] 2016-06-29 10:48
@chenziliang There is not at this time.

**Comment by chenziliang** [comment] 2016-06-29 13:56
Thanks @Lukasa ! May i ask if there is workaround ? I didn't run into broken pipe issue by using httplib2 by issuing the same request with the same payload.

**Comment by Lukasa** [comment] 2016-06-29 14:09
@chenziliang Are you sure they were the same? httplib2 and requests handle connections differently and set different headers, so it would be worth using something like Wireshark to confirm that the behaviours really are the same.

**Comment by chenziliang** [comment] 2016-06-29 14:19
From application level, probably they are the same, since same headers, payload etc. But will use wireshark to confirm. Thanks !

**Comment by huntc** [comment] 2016-11-04 03:47
I see that this issue is closed (https://github.com/kennethreitz/requests/issues/2422#issuecomment-91747721), but is it? [Subsequent comments](https://github.com/kennethreitz/requests/issues/2422#issuecomment-229322447) indicate that there's a problem that remains.

I've also just experienced the issue where a server doesn't consume the POST request, but replies with an error (the request was invalid) and then closes down the socket. The server is permitted to do this as it has also indicated a `Connection: close` in its reply.

As consequence my user receives a `BrokenPipeError` in place of the HTTP error returned by the server.

**Comment by Lukasa** [comment] 2016-11-04 08:29
@huntc The ultimate problem is that Requests currently has no way to detect that a response has arrived and abort processing of the request. httplib just doesn't let us in at that low a level. The only fix to your problem is to remove httplib from the equation, and while that's a thing we're working on it represents a really pretty major change to urllib3 and to Requests. It'll take a while to happen.

**Comment by huntc** [comment] 2016-11-04 12:30
Thanks for the explanation. Isn't the issue still technically an issue that remains though, and remain so until it is fixed? Had I first seen that the issue was open then it would've prevented me from wading through the comments only to discover that it is still an issue? Seeing that the issue was closed initially distracted me from treating it as a requests one, and caused me to spend time in the server, which ends up doing the right thing. I appreciate that you might not be able to fix this for a while though. Thanks.

**Comment by Lukasa** [comment] 2016-11-04 12:35
It depends on what your definition of this issue is. We can keep a ticket open for the general case of "requests doesn't handle early 4XX errors during requests with large bodies", but that's not what this issue was really about, and the original poster of this issue is totally AWOL. That's fundamentally why it was closed: this issue is a confused mess of different discussions, none of which is actually the issue you're discussing and encountering.

_Usually_, when people encounter this issue, the _actual_ problem they have is fixable: they're doing something to trigger a 4XX response from a server, and they should un-do that. That's why we closed the issue.

**Comment by huntc** [comment] 2016-11-04 12:47
Fair call!

I think in general the issue is that the request lib cannot handle a reply from the server while in the midst of sending its request payload. 

Our server will consume the first part of a multipart request and validate it before continuing to read the remainder. If it finds that the part is invalid then it will reply without consuming the remainder of the request. 

This is a valid 1.1 scenario of course. If you'd like me to open another issue then I'd be happy to. Otherwise I'll leave you alone. Thanks!

**Comment by Lukasa** [comment] 2016-11-04 12:54
So I agree that the issue we're discussing here is a real Requests problem. We can open a ticket for that, but the reality is that such a ticket is only of value in the sense that it says "Yes, we know there is a problem. No, we have no timeline for fixing it." It has been _my experience_ that issues like this are mostly a magnet for a hoard of "is this fixed yet" questions, which repeatedly require the answer "no".

If you want to open such a ticket, I won't close it. =) I will, however, almost certainly lock the conversation because any conversation on that ticket is unlikely to be of much value. In the meantime, there is work underway to try to get to a place where we can resolve this problem, but we're simply not there yet and unlikely to be any time soon.

Ultimately it's up to you. =)

**Comment by DavidMcLaughlin** [comment] 2016-11-29 23:14
This is a fairly serious issue when using Kerberos (with requests-kerberos), since it returns a 401 challenge as part of the normal negotiation process.

**Comment by Lukasa** [comment] 2016-11-30 09:12
@DavidMcLaughlin We know it's a problem, we know it affects lots of people, and we know that the amount of work that is required to fix it is really *very* substantial. There is no amount of reprioritisation that will get this moved up the list because the work required is O(months) of time. I am currently working on it in and amongst my many other maintenance duties.

As I noted in my above comment, I warned that tickets like this are unlikely to be of much value because of a hoard of "me too" comments. Now that they have begun, I am immediately locking this issue to further discussion.
