### ISSUE TITLE
URL has an invalid label when requesting https://r8---sn-q4f7snss.googlevideo.com

### ISSUE THREAD

**Issue by aploium** [kennethreitz/requests#3715] opened 2016-11-22 11:26 UTC
```python
>>> import requests
>>> requests.get("https://r8---sn-q4f7snss.googlevideo.com")
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 370, in prepare_url
    host = idna.encode(host, uts46=True).decode('utf-8')
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/idna/core.py", line 355, in encode
    result.append(alabel(label))
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/idna/core.py", line 276, in alabel
    check_label(label)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/idna/core.py", line 253, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
requests.packages.idna.core.InvalidCodepoint: Codepoint U+0027 at position 2 of "b'r8---sn-q4f7snss'" not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 372, in prepare_url
    raise InvalidURL('URL has an invalid label.')
requests.exceptions.InvalidURL: URL has an invalid label.
```

requests 2.12.0

**Comment by Lukasa** [comment] 2016-11-22 11:53
When reporting bugs in open source projects *please* check the open issues first before opening a new one. If you had done that you'd have found literally the text "URL has an invalid label" next to the word "Bug" four entries down.

Duplicate of #3683, closing accordingly.

**Closed by Lukasa** 2016-11-22 11:53 UTC
