### ISSUE TITLE
Performance issues while working behind a proxy where no proxy is needed.

### ISSUE THREAD

**Issue by Tset-Noitamotua** [kennethreitz/requests#3294] opened 2016-06-08 09:41 UTC
Hi, plz have a look at this [issue #116](https://github.com/bulkan/robotframework-requests/issues/116)  with [robotframework-requests](https://github.com/bulkan/robotframework-requests) library, take particular notice of my [second comment](https://github.com/bulkan/robotframework-requests/issues/116#issuecomment-224537034), it might be related to 'requests'.

Cheers
Tset

**Comment by Lukasa** [comment] 2016-06-08 09:42
This is a known issue: it's a duplicate of #2988.

**Closed by Lukasa** 2016-06-08 09:42 UTC
