### ISSUE TITLE
requests does not respect the timeout set by socket.setdefaultimeout

### ISSUE THREAD

**Issue by ikatson** [kennethreitz/requests#2555] opened 2015-04-21 18:02 UTC
Steps to reproduce:

```py
import socket
import requests

socket.setdefaultimeout(0.0001)
# Expected this to raise exception, but it does not.
requests.get('http://google.com')

# These 2 raise an exception
requests.get('http://google.com', timeout=socket.gettimeout())
requests.get('http://google.com', timeout=socket._GLOBAL_DEFAULT_TIMEOUT)
```

Looks like the default "None" value is propagated to urllib3, which has ```socket._GLOBAL_DEFAULT_TIMEOUT``` set as the default timeout.

Is this by-design or a bug?

**Comment by sigmavirus24** [comment] 2015-04-21 18:43
Duplicate of #2228. Please check open issues in the future for possible duplicates.

**Closed by sigmavirus24** 2015-04-21 18:43 UTC
