### ISSUE TITLE
SSL Error 14077438

### ISSUE THREAD

**Issue by sergedroz** [kennethreitz/requests#2604] opened 2015-05-17 18:03 UTC
Certain cloudflare websites cannot be access with requests. I have dis problem across different distros. Same problem here: https://github.com/SiCKRAGETV/sickrage-issues/issues/1231

requests.get('https://sceneaccess.eu')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

**Comment by Lukasa** [comment] 2015-05-17 18:10
Where have you installed requests from, and what versions do you have installed?

**Comment by Lukasa** [comment] 2015-05-17 18:20
This is likely because you're linked against an old version of OpenSSL. Can you run this for me and show me the output?

``` bash
python -c 'from cryptography.hazmat.backends.openssl.backend import backend; print backend.openssl_version_text()'
```

**Comment by Lukasa** [comment] 2015-05-17 18:23
Yup, I can confirm: if I have PyOpenSSL compiled against OpenSSL 0.9.8 the handshake fails because there are no overlapping cipher suites. If I compile against OpenSSL 1.0.2, however, the handshake succeeds.

**Comment by Hasimir** [comment] 2015-05-17 20:48
@Lukasa it's probably best to use print() for instructions like that in case the end user is on a distro which has changed the sym link for python to point to python 3 instead of 2.

As a side note, I generally recompile python after installing a new version of OpenSSL, so I was a little surprised to see my workstation here reporting the version as 1.0.2 instead of 1.0.2a and it turns out that the cryptography module requires a force reinstall to detect that change in addition to whatever is done to the python installation (which normally includes byte compiling installed modules), it would be quite easy for anyone to overlook that even after upgrading OpenSSL.

**Comment by Lukasa** [comment] 2015-05-17 20:58
> it's probably best to use print() for instructions like that in case the end user is on a distro which has changed the sym link for python to point to python 3 instead of 2.

That's not really relevant. =) The number of users using Python 3 instead of Python 2 is very low, and I trust that most users capable of reporting bugs on this bug tracker are also capable of translating this extremely common line of code into the correct syntax for their platform. Given that `print()` won't work on Python 2 without an appropriate **future** import, I'm choosing to optimise for the more likely case.

Regardless, I think we can close this. @sergedroz, your OpenSSL is too old. If you're using pyOpenSSL, please reinstall cryptography linked against a more modern OpenSSL. If you're not, please upgrade to a newer version of OpenSSL and then rebuild Python.

**Closed by Lukasa** 2015-05-17 20:58 UTC
