### ISSUE TITLE
Add requests.Session(timeout) parameter

### ISSUE THREAD

**Issue by giampaolo** [kennethreitz/requests#3994] opened 2017-04-30 15:28 UTC
...as a parameter which gets inherited globally by `get()` and other HTTP methods.

```
session = requests.Session(timeout=30)
session.get(...)
session.get(...)
```

Would be equivalent to:

```
session = requests.Session()
session.get(..., timeout=30)
session.get(..., timeout=30)
```

Thoughts?

**Comment by Lukasa** [comment] 2017-04-30 15:58
Thanks for opening this! This is a duplicate of #3341: please read the discussion there for more.

**Closed by Lukasa** 2017-04-30 15:58 UTC

**Comment by giampaolo** [comment] 2017-04-30 15:59
Oh sorry about that.
