### ISSUE TITLE
ImportError: No module named 'requests.packages' for version 2.16.0

### ISSUE THREAD

**Issue by yash-nisar** [kennethreitz/requests#4071] opened 2017-05-27 09:07 UTC
```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from requests.packages.urllib3.poolmanager import PoolManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'requests.packages'
```
The following import statement used to work for the older version `2.14.2` but fails for the latest version `2.16.0`

**Comment by Lukasa** [comment] 2017-05-27 09:17
This is a duplicate of #4069: please check open issues before reporting bugs. 😉

**Closed by Lukasa** 2017-05-27 09:17 UTC

**Comment by yash-nisar** [comment] 2017-05-27 09:19
My bad.

**Comment by kennethreitz** [comment] 2017-05-27 14:11
Note: code that was written to import against the requests.packages namespace previously will have to import code that rests at this module-level now.

For example:

    from requests.packages.urllib3.poolmanager import PoolManager

Will need to be re-written to be:

    from requests.packages import urllib3
    urllib3.poolmanager.PoolManager

Or, even better:

    from urllib3.poolmanager import PoolManager

**Comment by kennethreitz** [comment] 2017-05-27 15:08
Requests v2.16.2 is now out, which makes the above code no longer necessary.
