### ISSUE TITLE
 Invalid environment marker

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [kennethreitz/requests#4012] opened 2017-05-10 11:32 UTC
requests 2.14+ centos7 py27

```
omeroweb_1  |   Running setup.py egg_info for package requests
omeroweb_1  |     error in requests setup command: Invalid environment marker: platform_system == "Windows" and python_version<"3.3"
omeroweb_1  |     Complete output from command python setup.py egg_info:
omeroweb_1  |     error in requests setup command: Invalid environment marker: platform_system == "Windows" and python_version<"3.3"
```

**Comment by Lukasa** [comment] 2017-05-10 11:34
Are you sure you receive the exact same output for 2.14 and 2.14.1? Because this appears to be a duplicate of #4006, which should have been resolved by #4007 in 2.14.1.

**Comment by atarkowska** [comment] 2017-05-10 11:34
yes because https://github.com/ome/omero-mapr/blob/master/requirements.txt#L1

I have to `requests==2.13.0`

**Comment by Lukasa** [comment] 2017-05-10 11:35
@aleksandra-tarkowska When are you encountering the error. Right now?

**Comment by Lukasa** [comment] 2017-05-10 11:35
What version of pip are you using to install requests? What version of setuptools is currently installed?

**Comment by atarkowska** [comment] 2017-05-10 11:42
yes, at the moment, it is new container

```
omeroweb_1  | Downloading/unpacking requests==2.14.1 (from omero-mapr==0.1.14->-r /home/omero/requirements-webapps.txt (line 2))
omeroweb_1  |   Running setup.py egg_info for package requests
omeroweb_1  |     error in requests setup command: Invalid environment marker: sys_platform == "win32" and python_version<"3.3"
omeroweb_1  |     Complete output from command python setup.py egg_info:
omeroweb_1  |     error in requests setup command: Invalid environment marker: sys_platform == "win32" and python_version<"3.3"
omeroweb_1  | 
```

CentOS 7
```
[omero@496158a7ba55 ~]$ easy_install --version
setuptools 0.9.8
[omero@496158a7ba55 ~]$ pip --version
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
```

**Comment by atarkowska** [comment] 2017-05-10 11:43
default rpm provided by yum

**Comment by Lukasa** [comment] 2017-05-10 11:43
Ok, so I think your setuptools is too old and unsupported by Requests. Try doing `pip install -U setuptools`: that should resolve your issue. This is a duplicate of #4006.

**Comment by sigmavirus24** [comment] 2017-05-10 11:56
I agree. This is a duplicate of #4006. I'll also add that it appears that you're using easy_install to install requests. That may have worked even recently but has not been supported for *years*. Please use pip to install requests.

**Closed by sigmavirus24** 2017-05-10 11:56 UTC

**Comment by remram44** [comment] 2017-05-10 15:18
I'm running into this on Travis. Installing 'requests' fails since today with:
```
error: Setup script exited with error in requests setup command: Invalid environment marker: sys_platform == "win32" and python_version<"3.3"
```
I am confused since this job is running on Linux with Python 3.4.

**Comment by remram44** [comment] 2017-05-10 15:18
Job URL: https://travis-ci.org/remram44/usagestats/jobs/230593204

**Comment by Lukasa** [comment] 2017-05-10 15:19
@remram44 Try again, we shipped a 2.14.2 release that should have resolved your issue.

**Comment by atarkowska** [comment] 2017-05-10 15:28
👍 
```
  Running setup.py install for requests
    
    warning: no files found matching 'test_requests.py'
Successfully installed omero-mapr requests
```

**Comment by remram44** [comment] 2017-05-10 15:30
New build passed, thanks for the quick turnaround!
